# Codecov configuration for Rust Jira MCP
# https://docs.codecov.com/docs/codecov-yaml

coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 70%
        informational: true
    patch:
      default:
        target: 80%
        threshold: 70%
        informational: true

# Ignore test utilities from coverage calculation
ignore:
  - "src/test_utils/**"
  - "src/test_usage.rs"
  - "tests/**"
  - "**/*_test.rs"
  - "**/*_tests.rs"
  - "examples/**"
  - "target/**"

# Comment configuration for PRs
comment:
  layout: "header,diff,files,footer"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

# Notifications
notify:
  webhook:
    url: "https://codecov.io/gh/${{ github.repository }}/settings/integrations"
    after_n_builds: 3
    wait_for_ci: true

# Coverage reports
codecov:
  require_ci_to_pass: yes
  max_report_age: 12h
  max_upload_age: 12h
  max_upload_attempts: 2

# Flags for different types of tests
flags:
  unittests:
    paths:
      - "src/"
    carryforward: true
  integration:
    paths:
      - "tests/"
    carryforward: false

# Coverage thresholds by file type
coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 70%
        informational: true
        only_pulls: true
    patch:
      default:
        target: 80%
        threshold: 70%
        informational: true
        only_pulls: true
