[hooks]
pre-commit = [
    "cargo fmt",
    "cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic",
    "./scripts/check-allows.sh",
    "cargo test --all-targets --all-features"
]

[hooks.pre-push]
commands = [
    "cargo fmt",
    "cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic",
    "./scripts/check-allows.sh",
    "cargo test --all-targets --all-features"
]

[hooks.commit-msg]
commands = [
    "cargo clippy --all-targets --all-features -- -D warnings -W clippy::pedantic"
]
